/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import state.ProductOrder;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * @author tatsuya
 */
public class MainView extends JFrame {

    /**
     * Creates new form MainView
     */
    private DefaultTableModel tableModel;

    public MainView() {
        initComponents();
        this.tableModel = (DefaultTableModel) this.tblOrder.getModel();
        super.setVisible(true);
        super.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new JTabbedPane();
        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        tblOrder = new JTable();
        btnCreateBill = new JButton();
        jPanel2 = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        tblOrder.setModel(new DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Order ID", "Meal ID", "Creation Date", "Payment Type", "Address"
                }
        ));
        jScrollPane1.setViewportView(tblOrder);

        btnCreateBill.setText("Create Bill");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateBill, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 77, Short.MAX_VALUE)
                                .addComponent(btnCreateBill, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 318, GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Order Processing", jPanel1);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 454, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Development", jPanel2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCreateBill;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    private JTabbedPane jTabbedPane1;
    private JTable tblOrder;

    // End of variables declaration//GEN-END:variables
    public void setBtnCreateBillListener(ActionListener listener) {
        this.btnCreateBill.addActionListener(listener);
    }

//    public void showDataToTable(List<FoodOrder> orderList) {
//        orderList.forEach(order -> {
//            this.tableModel.addRow(new Object[]{
//                    order.getID(),
//                    order.getMeal().getID(), order.getCreationDate(),
//                    order.getPaymentType(), order.getAddress()
//            });
//        });
//    }

    public void showDataToTable(List<ProductOrder> orderList) {
        orderList.forEach(order -> {
            this.tableModel.addRow(new Object[]{
                    order.getOrder().getID(),
                    order.getOrder().getMeal().getID(), order.getOrder().getCreationDate(),
                    order.getOrder().getPaymentType(), order.getOrder().getAddress()
            });
        });
    }


    public int getTableSelectedIndex() {
        return this.tblOrder.getSelectedRow();
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void removeRow(int index) {
        this.tableModel.removeRow(index);
        super.repaint();
    }
}
